channels:
  - conda-forge
  - defaults
dependencies:
  - av
  - git
  - ipywidgets
  - matplotlib>=3.1
  - nbdime       # optional: nbdime extensions --enable
  - nbstripout   # optional: nbstripout --install
  - notebook
  - numpy
  - packaging
  - pandas
  - pip
  - python>=3
  - pyqt
  - pyyaml
  - quantities
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tqdm
  - pip:
    - elephant>=0.6.2
    - pylttb
    - spm1d
    - git+https://github.com/NeuralEnsemble/python-neo.git
    - git+https://github.com/NeuralEnsemble/ephyviewer.git
    - git+https://github.com/jpgill86/tridesclous.git@experimental
    - git+https://github.com/jpgill86/neurotic.git
