channels:
  - conda-forge
  - defaults
dependencies:
  - av
  - ipywidgets
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pip
  - python>=3
  - pyyaml
  - quantities
  - seaborn
  - statsmodels
  - tqdm
  - pip:
    - axographio>=0.3.1
    - neo>=0.7.1
    - pylttb
    - spm1d
    - git+https://github.com/jpgill86/ephyviewer.git@experimental
    - git+https://github.com/NeuralEnsemble/elephant.git@master
    - git+https://github.com/jpgill86/tridesclous.git@experimental
