channels:
  - conda-forge
  - defaults
dependencies:
  - av
  - ipykernel=4.10.0    # workaround for tridesclous and kernel.json bug
  - ipywidgets
  - matplotlib
  - notebook
  - numpy
  - pandas
  - python>=3
  - pyyaml
  - quantities
  - scikit-learn=0.19.2 # workaround for tridesclous
  - pip:
    - git+https://github.com/NeuralEnsemble/python-neo.git@master
    - git+https://github.com/jpgill86/ephyviewer.git@experimental
    - git+https://github.com/tridesclous/tridesclous.git@master
    - axographio
    - elephant
    - spm1d
