channels:
  - conda-forge
  - defaults
dependencies:
  - git
  - ipywidgets
  - matplotlib>=3.1
  - nbdime       # optional: nbdime extensions --enable
  - nbstripout   # optional: nbstripout --install
  - neurotic
  - notebook
  - numpy
  - pandas
  - pip
  - python>=3.6
  - python-neo>=0.8.0
  - quantities
  - r-effsize
  - r-rrcov
  - rpy2==2.9.4  # newer builds for Windows are broken
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tqdm
  - pip:
    - elephant>=0.6.2
    - pylttb
    - spm1d
    - git+https://github.com/jpgill86/tridesclous.git@experimental
