channels:
  - conda-forge
  - defaults
dependencies:
  - av
  - ipykernel=4.10.0 # workaround for tridesclous bug
  - ipywidgets
  - matplotlib
  - notebook
  - numpy
  - pandas
  - python>=3
  - pyyaml
  - quantities
  - seaborn
  - statsmodels
  - pip:
    - axographio>=0.3.1
    - neo>=0.7.0
    - pylttb
    - spm1d
    - git+https://github.com/jpgill86/ephyviewer.git@experimental
    - git+https://github.com/jpgill86/elephant.git@experimental
    - git+https://github.com/tridesclous/tridesclous.git@master
