channels:
  - conda-forge
  - defaults
dependencies:
  - av
  - git
  - ipywidgets
  - matplotlib
  - nbdime       # optional: nbdime extensions --enable
  - nbstripout   # optional: nbstripout --install
  - notebook
  - numpy
  - pandas
  - pip
  - python>=3
  - pyyaml
  - quantities
  - scipy
  - seaborn
  - statsmodels
  - tqdm
  - pip:
    - axographio>=0.3.1
    - elephant>=0.6.2
    - neo>=0.7.1
    - pylttb
    - spm1d
    - git+https://github.com/jpgill86/ephyviewer.git@experimental
    - git+https://github.com/jpgill86/tridesclous.git@experimental
